/*
 * This source file was generated by the Gradle 'init' task
 */
package com.personal.HTTPServer;

public class App {
    public static void main(String[] args) {
        Server server = new Server();
        server.start();
    }
}
